### ISSUE TITLE
Why do pERC replace "peth" with "pweth" during initialization?

### ISSUE THREAD

**Issue by Lebed-kun** [provable-things/ptokens.js-v1#6]
https://github.com/provable-things/ptokens.js/blob/master/packages/ptokens-perc20/src/index.js#L47

**Comment by allemanfredi** [comment]
If you want to issue by sending ETH you should use pETH, otherwise if you use WETH you should use pWETH (remember to approve the amount before calling .issue(...) if you use WETH). 
Basically what happens hunder the hood when you send ETH ,is that our contract converts ETH to WETH which will be pegged.
Technically the token that is pegged is WETH but we give the possibility to use ETH (instead of WETH) which will be converted to WETH before being pegged, so on the pNetwork node side it is seen as WETH even if you get worse using ETH.
